build:trusty:
  image: js-er-code.jsc.nasa.gov:5005/ci_build/ubuntu_trusty_with_nasa_certs:latest
  script:
    - apt update
    - apt install -y git cmake build-essential libzmq3-dev uuid-dev
    - mkdir build
    - cd build
    - cmake .. && make

build:xenial:
  image: js-er-code.jsc.nasa.gov:5005/ci_build/ubuntu_xenial_with_nasa_certs:latest
  script:
    - apt update
    - apt install -y git cmake build-essential libzmq3-dev uuid-dev    
    - mkdir build
    - cd build
    - cmake .. && make

build:windows:
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017" ..
    - cmake --build .
  tags:
    - lager
    - windows
