stages:
  - build
  - coverage

trusty:
  stage: build
  image: js-er-code.jsc.nasa.gov:5005/lager/lager_image_base_trusty:stable
  script:
    - mkdir build
    - cd build
    - cmake .. && make

xenial:
  stage: build
  image: js-er-code.jsc.nasa.gov:5005/lager/lager_image_base_xenial:stable
  script:   
    - mkdir build
    - cd build
    - cmake .. && make

windows:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017" ..
    - cmake --build .
  tags:
    - lager
    - windows

gcov:
  stage: coverage
  image: js-er-code.jsc.nasa.gov:5005/lager/lager_image_base_xenial:stable
  script:   
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug .. && make lager_coverage
