stages:
  - prebuild
  - build
  - deploy

trusty:
  stage: build
  image: js-er-code.jsc.nasa.gov:5005/lager/lager_image_base_trusty:stable
  script:
    - mkdir build
    - cd build

xenial:
  stage: build
  image: js-er-code.jsc.nasa.gov:5005/lager/lager_image_base_xenial:stable
  script:   
    - mkdir build
    - cd build
    - cmake .. && make && make test

windows:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 15 2017" ..
    - cmake --build . --config Debug
    - ctest -C Debug
  tags:
    - lager
    - windows

static-analysis:
  stage: prebuild
  image: js-er-code.jsc.nasa.gov:5005/lager/lager_image_base_xenial:stable
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make cppcheck

coverage:
  stage: build
  image: js-er-code.jsc.nasa.gov:5005/lager/lager_image_base_xenial:stable
  script:   
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage .. && make && make run_coverage
  coverage: '/lines[\.]+\: (\d+\.\d+)\%/'
  artifacts:
    paths:
      - build/coverage/

report:
  image: js-er-code.jsc.nasa.gov:5005/ci_build/ubuntu_xenial_with_nasa_certs_and_python
  stage: deploy
  dependencies: 
    - coverage
  script:
    - git clone -b feature/generic-file-support git@js-er-code.jsc.nasa.gov:ci_build/ci_scripts.git
    - cd ci_scripts 
    - pip install .
    - cd ..
    - artifactory_upload generic $CI_PROJECT_PATH/$CI_COMMIT_REF_SLUG build/coverage
  only:
    - master
    - develop
